#ifndef ADD_H
#define ADD_H
extern void start_mpi(int argc, char **argv);
extern void elastic_read_input();
extern void anisotropic_input();
extern void calc_c_alpha_delta();
extern void prepare_U1_new (double *fieldE1, double *fieldE2);
extern void prepare_U2_new (double *phiE2, double *fieldE1, double *fieldE2);
extern void correct_U_new (double *fieldE, double *fieldE1);
extern void central_finite_volume (int n, double *fieldci1, double *ftr, double *fieldEr);
extern void ac_calc_F2(int n);
extern void alloc_vars();
extern void init_vars();
extern void define_mpi_type();
extern void conv_init_transfer();
extern void sw_cart_creat();
extern void init_para();
extern void read_matrices();
extern void init_field ();
extern void elastic_malloc();
extern void elastic_calculate_BN();
extern void elastic_calculate();
extern void check_soln_new (double tt);
extern void elastic_transfer();
extern void transfer ();
extern void calc_mu();
extern void ac_calc_FU (int n, double *fieldE1);
extern void ch_calc_FU (int n, double *fieldCI1);
extern void PUX (double *MPXI, double *fieldE, double *fieldEt, double *fieldEp);
extern void PUY (double *MPYI, double *fieldEt, double *fieldE, double *fieldEp);
extern void PUZ (double *MPZI, double *fieldE, double *fieldEt, double *fieldEp, double *fieldEt1);
extern void ac_updateU_new (int n, double *fieldEt, double *fieldEp);
extern void zxy_xyz (double *fieldEt, double *fieldE);
extern void ch_updateU_new (int n, double *fieldCIt, double *fieldCIp);
extern void elastic_free();
extern void dealloc_vars ();
extern void close_mpi ();
extern void top_bottom_pack (double *felas, double *fieldCIs_top, double *fieldCIs_bottom, double *fieldCIr_front, double *fieldCIr_back);
extern void left_right_pack (double *felas, double *fieldCIs_left, double *fieldCIs_right, double *fieldCIr_top, double *fieldCIr_bottom, double *fieldCIr_front, double *fieldCIr_back);
extern void unpack (double *felas, double *fieldCIr_left, double *fieldCIr_right, double *fieldCIr_top, double *fieldCIr_bottom, double *fieldCIr_front, double *fieldCIr_back);
extern void enlarge (double *felase_left, double *felase_right, double *felase_top, double *felase_bottom, double *felase_front, double *felase_back, double *fieldCIr_left, double *fieldCIr_right, double *fieldCIr_top, double *fieldCIr_bottom, double *fieldCIr_front, double *fieldCIr_back);
extern void check_max(double *felas);
extern double EF();
extern double AC_f(int n);
extern double CH_f(int n);
extern void write_Bn(double *f);;
#endif 
